---
- name: awx-testing
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Get list of installed collections
    command: ansible-galaxy collection list
    register: installed_collections

  - name: Print list of installed collections
    debug:
      var: installed_collections.stdout_lines

  - name: get smc files
    command: touch /var/ansible/test1.txt
    register: smc
