---
- name: Delete files in /var/ansible
  hosts: localhost
  gather_facts: no
  become: yes # Use sudo to ensure we have the permissions to write to /var/ansible
  tasks:
    - name: Ensure the /var/ansible directory exists
      ansible.builtin.file:
        path: /var/ansible
        state: directory
        mode: "0755" # Sets the permissions of the directory

    - name: Delete multiple files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/ansible/test1.txt
        - /var/ansible/test.txt
        - /var/ansible/example.txt
        - /var/ansible/example-test.txt
        - /var/ansible/example-test-2.txt
