---
- name: awx-testing
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
  - name: Get list of installed collections
    command: ansible-galaxy collection list
    register: installed_collections

  - name: Print list of installed collections
    debug:
      var: installed_collections.stdout_lines

  ###
  - name: Ensure the /var/ansible directory exists
    ansible.builtin.file:
       path: /var/ansible
       state: directory
       mode: "0755"
  ###
  #- name: Create a file in /var/ansible
  #  ansible.builtin.copy:
  #    dest: /var/ansible/example.txt
  #    content: |
  #      Hello, this is a test file.
  #      This file was created by an Ansible playbook.
  #    mode: "0644"
