---
- name: awx-testing
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Get list of installed collections
    command: ansible-galaxy collection list
    register: installed_collections

  - name: Print list of installed collections
    debug:
      var: installed_collections.stdout_lines

  - name: Pause for 5 minute
    ansible.builtin.pause:
      minutes: 5

  - name: get smc files
    command: cat /usr/share/ansible/collections/ansible_collections/expedient/smc/plugins/module_utils/smc.py
    register: smc

  - name: print smc
    debug:
      var: smc
